config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'

  get '/oauth/callback', to: 'o_auth#callback'

  resources :photos, only: [:index, :new, :create]
  post '/photos/tweet', to: 'photos#tweet'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  validates :title, presence: true, length: { maximum: 30 }

  belongs_to :user

  has_one_attached :image
end

app/models/session.rb
class Session
  include ActiveModel::Model

  attr_accessor :username, :password

  validates :username, presence: true
  validates :password, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates_presence_of :username, :password
  validates_uniqueness_of :username

  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :user_logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_logged_in?
    !!current_user
  end
end

app/controllers/o_auth_controller.rb
require 'net/http'

class OAuthController < ApplicationController
  def callback
    token = exchange_code_for_token(params[:code])

    session[:access_token] = token

    redirect_to photos_path
  end

  private

  def exchange_code_for_token(code)
    uri = URI(MyTweet.token_request_url)

    req = Net::HTTP::Post.new(uri)
    req.set_form_data('code' => code,
                      'client_id' => MyTweet.client_id,
                      'client_secret' => MyTweet.client_secret,
                      'response_type' => 'token',
                      'redirect_uri' => 'http://localhost:3000/oauth/callback',
                      'grant_type' => 'authorization_code')
    
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = (uri.scheme == 'https')
    res = http.request(req)

    body = JSON.parse(res.body)

    body['access_token']
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :require_user, only: [:index, :new]

  def index
    @photos = current_user.photos.order(created_at: :desc)
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.user_id = current_user.id

    title = params[:photo][:title]
    image = params[:photo][:image]

    if @photo.valid? && !image.nil?
      @photo.save!

      redirect_to photos_path
    else
      flash.now[:image_missing] = "画像ファイルを入力してください" if image.nil?

      render :new
    end
  end

  def tweet
    photo = Photo.find(params[:photo_id])
    MyTweet.tweet(session[:access_token], photo.title, url_for(photo.image))

    redirect_to photos_path
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :image)
  end

  def require_user
    redirect_to login_path unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @session = Session.new
  end

  def create
    @session = Session.new(session_params)

    if @session.valid?
      user = User.find_by(username: params[:session][:username])

      if user && user.authenticate(params[:session][:password])
        reset_session
        session[:user_id] = user.id

        redirect_to photos_path
      else
        flash.now[:error] = "入力されたユーザー名やパスワードが正しくありません。" + 
                            "確認してからやりなおしてください。"

        render :new
      end
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    reset_session

    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kadai</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/photos/index.erb
<h1>写真一覧</h1>

<p><%= link_to 'MyTweet Appと連携する', MyTweet.code_request_url %></p>

<p><%= link_to '写真を追加する', new_photo_path %></p>

<ul class="photo-list">
  <% @photos.each do |photo| %>
    <li>
      <figure>
        <figcaption>
          <%= photo.title %>
        </figcaption>
        <%= image_tag url_for(photo.image), height: "160", alt: photo.title %>
        <%= button_to 'Tweet', photos_tweet_path(photo_id: photo.id) %>
      </figure>
    </li>
  <% end %>
</ul>

app/views/photos/index.html.erb
<h1>写真一覧</h1>

<p><%= link_to "MyTweet Appと連携する", MyTweet.code_request_url %></p>

<p><%= link_to "写真を追加する", new_photo_path %></p>

<ul class="photo-list">
  <% @photos.each do |photo| %>
    <li>
      <figure>
        <figcaption>
          <%= photo.title %>
        </figcaption>
        <%= image_tag url_for(photo.image), height: '160', alt: photo.title %>
        <%= button_to "ツイートする", photos_tweet_path(photo_id: photo.id) %>
      </figure>
    </li>
  <% end %>
</ul>

app/views/photos/new.erb
<h1>写真アップロード</h1>

<% if flash %>
  <ul>
    <% flash.each do |name, message| %>
      <li class="error-message">
        <%= message %>
      </li>
    <% end %>
  </ul>
<% end %>

<%= form_for @photo, url: {action: "create"}, html: {class: "form"} do |f| %>
  <div>
    <%= f.label :title ,  "タイトル" %>
    <%= f.text_field :title%>
  </div>
  <div>
    <%= f.label :image, "画像ファイル"  %>
    <%= f.file_field :image %>
  </div>
  <div>
    <%= f.submit "アップロード" %>
    <%= link_to 'キャンセル', photos_path %>
  </div>
<% end %>

app/views/photos/new.html.erb
<h1>写真アップロード</h1>

<%= render partial: 'shared/model_validation_messages', locals: {model: @photo} %>
<%= render 'shared/flash_messages' %>

<%= form_for @photo, url: {action: 'create'}, html: {class: 'form'} do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title%>
  </div>
  <div>
    <%= f.label :image  %>
    <%= f.file_field :image %>
  </div>
  <div>
    <%= f.submit "アップロード" %>
    <%= link_to "キャンセル", photos_path %>
  </div>
<% end %>

app/views/shared/_flash_messages.erb
<% if flash %>
  <ul>
    <% flash.each do |name, message| %>
      <li class="error-message">
        <%= message %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_header.erb
<header class="site-header">
  <% if user_logged_in? %>
    <%= link_to "ログアウト", logout_path, method: 'POST' %>
  <% end %>
</header>

app/views/shared/_header.html.erb
<header class="site-header">
  <% if user_logged_in? %>
    <%= link_to "ログアウト", logout_path, method: 'POST' %>
  <% end %>
</header>

app/views/shared/_model_validation_messages.erb
<ul>
  <% model.errors.full_messages.each do |message| %>
    <li class="error-message">
      <%= message %>
    </li>
  <% end %>
</ul>